name: Python CI/CD para Render

on:
  push:
    branches: [main]

jobs:
  # lint:
  #   name: Linter (flake8)
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Clonar repositorio
  #       uses: actions/checkout@v3

  #     - name: Configurar Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.11"

  #     - name: Instalar flake8
  #       run: |
  #         pip install flake8

  #     - name: Ejecutar flake8
  #       run: |
  #         flake8 . --max-line-length=120 --ignore=E305,E0302
  test:
    name: Tests con pytest
    runs-on: ubuntu-latest

    env :
      MAIL_DEFAULT_SENDER: ${ { secrets.MAIL_DEFAULT_SENDER } }

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar pytest
        run: |
          source venv/bin/activate
          pytest || echo "No hay pruebas definidas" 

  security:
    name: Análisis de seguridad (Bandit)
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar bandit
        run: |
          pip install bandit

      - name: Ejecutar bandit
        run: |
          bandit -r . -ll
          
  dependency-check:
    name: Análisis de dependencias (OWASP)
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Ejecutar Dependency-Check con Docker
        run: |
          mkdir -p reports
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/reports:/report \
            owasp/dependency-check \
            --project "Python App" \
            --scan /src \
            --format HTML \
            --out /report

      - name: Subir reporte
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

  zap-scan:
    name: Escaneo web (OWASP ZAP)
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:5000'  # Asegúrate que tu app corra ahí
          fail_action: false

      - name: Subir reporte ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: owasp-zap-report.html

  deploy:
    name: Desplegar en Render
    needs: [test, security, dependency-check, zap-scan]
    runs-on: ubuntu-latest

    steps:
      - name: Llamar al webhook de Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
